[tool.coverage.run]
branch = true
source = [ "opentelemetry/instrumentation/ollama" ]

[tool.coverage.report]
exclude_lines = ['if TYPE_CHECKING:']
show_missing = true

[tool.poetry]
name = "opentelemetry-if-instrumentation-ollama"
version = "0.25.6"
description = "OpenTelemetry Ollama instrumentation"
authors = [
  "Gal Kleinman <gal@traceloop.com>",
  "Nir Gazit <nir@traceloop.com>",
]
repository = "https://github.com/insightfinder/ifllmetry/tree/main/packages/opentelemetry-instrumentation-ollama"
license = "Apache-2.0"
readme = "README.md"

[[tool.poetry.packages]]
include = "opentelemetry/instrumentation/ollama"

[tool.poetry.dependencies]
python = ">=3.9,<4"
opentelemetry-api = "^1.25.0"
opentelemetry-instrumentation = ">=0.46,<0.49"
opentelemetry-semantic-conventions = "^0.46b0"
opentelemetry-if-semantic-conventions-ai = "0.3.6"

ollama = ">=0.2,<0.5"
[tool.poetry.group.dev.dependencies]
autopep8 = "^2.2.0"
flake8 = "7.1.1"
pytest = "^8.2.2"
pytest-sugar = "1.0.0"

[tool.poetry.group.test.dependencies]
pytest = "^8.2.2"
pytest-sugar = "1.0.0"
vcrpy = ">=6.0.1,<8.0.0"
pytest-recording = "^0.13.1"
pytest-asyncio = ">=0.23.7,<0.26.0"
opentelemetry-sdk = "^1.23.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
instruments = ["ollama"]

[tool.poetry.plugins."opentelemetry_instrumentor"]
ollama = "opentelemetry.instrumentation.ollama:OllamaInstrumentor"
